package com.envision.cucumbertest.bdd;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import org.junit.runner.RunWith;

/**
 * To run cucumber test.
 * <p>
 * <b>NOTE:</b> A JSON report with the name “json:target/cucumber-report.json” will be generated by Cucumber.
 * It is the input to Cucumber Report generator.
 * </P>
 * Cucumber automatically reads all directories under the package where it is configured.
 * Make sure all Cucumber related directories are under directory ‘bdd’ so that it is automatically glued to Cucumber execution context.
 * If you look at the source code, you can find all Cucumber related classes and step definitions are under com.envision.cucumbertest.bdd package in this example.
 *
 * @author john.bi
 */
@RunWith(CucumberReportRunner.class)
// ‘@CucumberOptions’ annotation is used to configure the directory that contains the feature files and output plugins.
@CucumberOptions(features = "classpath:features", plugin = {"pretty", "json:target/cucumber-report.json"})
public class CucumberTest {
}
